"""Initial migration

Revision ID: 156b40565e5b
Revises: 
Create Date: 2025-05-24 20:18:51.039292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156b40565e5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_actions',
    sa.Column('action_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('action_key'),
    sa.UniqueConstraint('action_type')
    )
    op.create_table('dim_devices',
    sa.Column('device_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('device_key'),
    sa.UniqueConstraint('device_type')
    )
    op.create_table('dim_locations',
    sa.Column('location_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('location_key'),
    sa.UniqueConstraint('location_name')
    )
    op.create_table('dim_users',
    sa.Column('user_key', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_key'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('fact_user_actions',
    sa.Column('action_event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_key', sa.Integer(), nullable=False),
    sa.Column('action_key', sa.Integer(), nullable=False),
    sa.Column('device_key', sa.Integer(), nullable=True),
    sa.Column('location_key', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_key'], ['dim_actions.action_key'], ),
    sa.ForeignKeyConstraint(['device_key'], ['dim_devices.device_key'], ),
    sa.ForeignKeyConstraint(['location_key'], ['dim_locations.location_key'], ),
    sa.ForeignKeyConstraint(['user_key'], ['dim_users.user_key'], ),
    sa.PrimaryKeyConstraint('action_event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_user_actions')
    op.drop_table('dim_users')
    op.drop_table('dim_locations')
    op.drop_table('dim_devices')
    op.drop_table('dim_actions')
    # ### end Alembic commands ###
