"""Init schema

Revision ID: 92f00d1650dd
Revises: 
Create Date: 2025-05-23 22:05:13.156566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92f00d1650dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_actions',
    sa.Column('action_key', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('action_key'),
    sa.UniqueConstraint('action_type')
    )
    op.create_table('dim_users',
    sa.Column('user_key', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_key'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('fact_user_actions',
    sa.Column('user_action_key', sa.Integer(), nullable=False),
    sa.Column('user_key', sa.Integer(), nullable=False),
    sa.Column('action_key', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['action_key'], ['dim_actions.action_key'], ),
    sa.ForeignKeyConstraint(['user_key'], ['dim_users.user_key'], ),
    sa.PrimaryKeyConstraint('user_action_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_user_actions')
    op.drop_table('dim_users')
    op.drop_table('dim_actions')
    # ### end Alembic commands ###
